### ISSUE TITLE
Vehicle plugin help

### ISSUE THREAD

**Issue by Elec11** [andreastpt/dash-VolvoS80#1]
Hey I stumbled upon this while looking into the Vehicle plugins for openDsh Might sound stupid but how do I use this?
after cloning to "/dash/plugins/vehicle" nothing shows up. Do I need to rebuild or activate this somewhere?

Asking here since you are active :)

**Comment by andreastpt** [comment]
Hi! You have to run `install.sh --dash` to compile it. Also keep in mind this is a very experimental plugin so far. 
(The window buttons open/close only the front passenger window for example)

**Comment by Elec11** [comment]
Thanks for the quick response! I was looking around for a make file or similar so. The install.sh but seemed like overkill. thanks for helping me out! also I don't even own a Volvo ;)
